#version 440 core

layout (local_size_x = 32, local_size_y = 32) in;

layout (binding = 0, rgba32f) readonly uniform image2D input_image;
layout (binding = 1) writeonly uniform image2D output_image;

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    vec4 texel = imageLoad(input_image, pixel);

    // Invert the pixel color
    texel = vec4(1.0) - texel;
    imageStore(output_image, pixel, texel);
}
